name: rabitati
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  dio: ^5.11.0
  google_fonts: ^8.2.1
  firebase_core: ^4.14.0
  cloud_firestore: ^6.9.0
  intl: ^0.20.3
  pdf: ^3.13.0
  printing: ^5.15.0
  firebase_auth: ^6.6.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/league_logo.png
    - assets/images/league_logo_splash.jpg
